# Generated by Django 4.2.13 on 2024-05-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('model_path', models.CharField(default='', max_length=255)),
                ('label_path', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
